//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RIRRREntities : DbContext
    {
        public RIRRREntities()
            : base("name=RIRRREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<employee> employees { get; set; }
    
        public virtual ObjectResult<GetDenseRank_Result> GetDenseRank()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDenseRank_Result>("GetDenseRank");
        }
    
        public virtual int GetDepartmentWithHighestSalary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDepartmentWithHighestSalary");
        }
    
        public virtual ObjectResult<Getempinformation_Result> Getempinformation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getempinformation_Result>("Getempinformation");
        }
    
        public virtual ObjectResult<GetEmployeeDetails_Result> GetEmployeeDetails(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeDetails_Result>("GetEmployeeDetails", iDParameter);
        }
    
        public virtual ObjectResult<GetEmployeesWithHighSalary_Result> GetEmployeesWithHighSalary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeesWithHighSalary_Result>("GetEmployeesWithHighSalary");
        }
    
        public virtual ObjectResult<GetRank_Result> GetRank()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRank_Result>("GetRank");
        }
    
        public virtual ObjectResult<RankEMP_Result> RankEMP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RankEMP_Result>("RankEMP");
        }
    }
}
